config/routes.rb
Rails.application.routes.draw do
  resources :receivables
  resources :billentries do
    collection do
      get 'company_data'
    end
  end
  resources :companies, only: [:show, :index, :create, :new]
  resources :trucks
  # get 'reports', to: 'reports#index'
  get 'bill_reports', to: 'reports#bill_report'
  get 'report_print', to: 'reports#report_print'

  resources :reports, only: [:index]
  # do
    # collection do
    #   get 'report_data'
    # end
  # end

  root to: 'welcome#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div class="main-header non-printable">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <%= link_to image_tag('logo.png', alt: 'Water HY-Drant Project'), root_path %>
        <p id="notice">
          <%= notice %>
        </p>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-3 text-center">
        <%= link_to trucks_path, 'data-no-turbolink' => true do %>
            <div class="truck-module">
            </div>
            <h3 class="truck-text">Truck Entry</h3>
        <% end %>
      </div>
      <div class="col-md-3 text-center">
        <%= link_to companies_path do %>
            <div class="cc-module">
            </div>
            <h3 class="cc-text">Company Entry</h3>
        <% end %>
      </div>
      <div class="col-md-3 text-center">
        <%=link_to billentries_path do %>
            <div class="bill-module">
            </div>
            <h3 class="bill-text">Bill Entry</h3>
        <% end %>
      </div>
      <div class="col-md-3 text-center">
        <%=link_to receivables_path do %>
            <div class="receiveable-module">
            </div>
            <h3 class="receiveable-text">Amount Entry</h3>
        <% end %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-3">
      </div>
      <div class="col-md-3 text-center m-t-m">
        <%= link_to reports_path do %>
            <div class="report-module">
            </div>
            <h3 class="report-text">Reports</h3>
        <% end %>
      </div>
      <div class="col-md-3 m-t-m text-center">
        <%= link_to destroy_user_session_path, method: :delete do %>
            <div class="exit">
            </div>
        <% end %>
        <h3 class="exit-text">Exit</h3>
      </div>
      <div class="col-md-3">
      </div>
    </div>

  </div>
</div>