config/routes.rb
Rails.application.routes.draw do
  resources :receivables
  resources :billentries do
    collection do
      get 'company_data'
    end
  end
  resources :companies, only: [:show, :index, :create, :new]
  resources :trucks
  # get 'reports', to: 'reports#index'
  get 'bill_reports', to: 'reports#bill_report'
  get 'report_print', to: 'reports#report_print'

  resources :reports, only: [:index]
  # do
    # collection do
    #   get 'report_data'
    # end
  # end

  root to: 'welcome#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all.where(secure: true, user_id: current_user.id)
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = current_user.companies.build
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = current_user.companies.build(company_params)
    if @company[:total_bill_amount].blank?
      @company[:total_bill_amount] = 0
    end
    if @company[:received_amount].blank?
      @company[:received_amount] = 0
    end
    @company[:secure] = true

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.update(secure: false)
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:company_name, :company_address, :contact_no, :company_reference, :total_bill_amount, :received_amount)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for(company) do |f| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="form-group">
  <div class="row">
    <div class="col-md-3">
      <div class="field">
        <%= f.label :company_name %>
        <%= f.text_field :company_name,class: "form-control", required: :true, placeholder: "Enter Company Name" %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="field">
        <%= f.label :company_address %>
        <%= f.text_area :company_address, class: "form-control", required: :true, placeholder: "Enter Company Address" %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="field">
        <%= f.label :contact_no %>
        <%= f.text_field :contact_no, class: "form-control", required: :true, placeholder: "Enter Contact No" %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="field">
        <%= f.label :company_reference %>
        <%= f.text_field :company_reference, class: "form-control", placeholder: "Company Reference Name" %>
      </div>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-4">
      <div class="field">
        <%= f.label :total_bill_amount %>
        <% if company.persisted? %>
          <%= f.text_field :total_bill_amount, value: number_with_precision(f.object.total_bill_amount, precision: 2) ,class: "form-control", disabled: true %>
        <% else %>
            <%= f.text_field :total_bill_amount, value: number_with_precision(f.object.total_bill_amount, precision: 2) ,class: "form-control", placeholder: "Company Total Bill Amount"%>
        <% end %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="field">
        <%= f.label :received_amount %>
        <% if company.persisted? %>
          <%= f.text_field :received_amount, value: number_with_precision(f.object.received_amount, precision: 2) ,class: "form-control", disabled: true%>
        <% else %>
          <%= f.text_field :received_amount, value: number_with_precision(f.object.received_amount, precision: 2) ,class: "form-control", placeholder: "Received Amount" %>
        <% end %>
      </div>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-4 col-md-offset-4 centered m-t-m text-center">
      <div class="actions">
        <%= f.submit class: "btn-success form-control" %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/companies/edit.html.erb
<div class="main-header non-printable">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <%= link_to image_tag('logo.png', alt: 'Water HY-Drant Project'), root_path %>
        <p id="notice">
          <%= notice %>
        </p>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-4">
        <h1>Edit Company Record</h1>
      </div>
      <div class="col-md-4">

      </div>
      <div class="col-md-4 col-md-offset-4 centered m-t-l text-center">
        <%= link_to '<< Back', companies_path, class: "btn-info form-control pull-right", style: "width:100px;" %>
      </div>
    </div>
    <hr>
    <%= render 'form', company: @company %>
  </div>
</div>

app/views/companies/index.html.erb
<div class="main-header non-printable">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <%= link_to image_tag('logo.png', alt: 'Water HY-Drant Project'), root_path %>
        <p id="notice">
          <%= notice %>
        </p>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-4">
        <h1>Companies</h1>
      </div>
      <div class="col-md-4">

      </div>
      <div class="col-md-4 m-t-m text-center">
        <%= link_to '+ New Company Entry', new_company_path, class: "btn-success form-control pull-right", style: "width:200px;" %>
      </div>
    </div>

    <table class="display" id="companies">
      <thead>
      <tr>
        <th>ID</th>
        <th>Company Name</th>
        <th>Company Address</th>
        <th>Contact No</th>
        <th>Company Reference</th>
        <th>Total Bill Amount</th>
        <th>Received Amount</th>
        <th>Net Balance</th>
      </tr>
      </thead>

      <tbody>
      <% @companies.each do |company| %>
          <tr>
            <td><%= link_to company.id, company %></td>
            <td><%= link_to company.company_name, company %></td>
            <td><%= link_to company.company_address, company %></td>
            <td><%= link_to company.contact_no, company %></td>
            <td><%= link_to company.company_reference, company %></td>
            <td><%= link_to number_to_currency(company.total_bill_amount, precision: 2, unit: 'PKR '), company %></td>
            <td><%= link_to number_to_currency(company.received_amount, precision: 2, unit: 'PKR '), company %></td>
            <td><%= link_to number_to_currency(company.total_bill_amount - company.received_amount, precision: 2, unit: 'PKR '), company %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
    <br>

  </div>
</div>

app/views/companies/new.html.erb
<div class="main-header non-printable">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <%= link_to image_tag('logo.png', alt: 'Water HY-Drant Project'), root_path %>
        <p id="notice">
          <%= notice %>
        </p>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-4">
        <h1>New Company Entry</h1>
      </div>
      <div class="col-md-4 col-md-offset-4 centered m-t-l text-center">
        <%= link_to '<< Back', companies_path, class: "btn-info form-control pull-right", style: "width:100px;" %>
      </div>
    </div>
    <hr>

    <%= render 'form', company: @company %>
  </div>
</div>

app/views/companies/show.html.erb
<div class="main-header non-printable">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <%= link_to image_tag('logo.png', alt: 'Water HY-Drant Project'), root_path %>
        <p id="notice">
          <%= notice %>
        </p>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-8">
        <h1>Review Company Record</h1>
      </div>
      <div class="col-md-4 m-t-l text-center">
        <%= link_to '<< Back', companies_path, class: "btn-info form-control pull-right", style: "width:100px;" %>
      </div>
    </div>
    <hr>
    <div class="row form-group">
      <div class="col-md-3">
        <h3>Company Name</h3>
        <input type="text" value="<%= @company.company_name %>" class="form-control" disabled>
      </div>
      <div class="col-md-3">
        <h3>Company Address</h3>
        <textarea class="form-control" disabled><%= @company.company_address %></textarea>
      </div>
      <div class="col-md-3">
        <h3>Contact No #</h3>
        <input type="text" value="<%= @company.contact_no %>" class="form-control" disabled>
      </div>
      <div class="col-md-3">
        <h3>Company Reference</h3>
        <input type="text" value="<%= @company.company_reference %>" class="form-control" disabled>
      </div>
    </div>
    <div class="row form-group">
      <div class="col-md-3">
        <h3>Total Bill Amount</h3>
        <input type="text" value="<%= number_to_currency(@company.total_bill_amount, precision: 2, unit: 'PKR ') %>" class="form-control" disabled>
      </div>
      <div class="col-md-3">
        <h3>Received Amount</h3>
        <input type="text" value="<%= number_to_currency(@company.received_amount, precision: 2, unit: 'PKR ')  %>" class="form-control" disabled>
      </div>
      <div class="col-md-3">
        <h3>Balance Amount</h3>
        <input type="text" value="<%= number_to_currency(@company.total_bill_amount - @company.received_amount, precision: 2, unit: 'PKR ')  %>" class="form-control" disabled>
      </div>
    </div>
    <br>
  </div>
</div>