config/routes.rb
Rails.application.routes.draw do
  resources :receivables
  resources :billentries do
    collection do
      get 'company_data'
    end
  end
  resources :companies, only: [:show, :index, :create, :new]
  resources :trucks
  # get 'reports', to: 'reports#index'
  get 'bill_reports', to: 'reports#bill_report'
  get 'report_print', to: 'reports#report_print'

  resources :reports, only: [:index]
  # do
    # collection do
    #   get 'report_data'
    # end
  # end

  root to: 'welcome#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/receivable.rb
class Receivable < ApplicationRecord
end

app/controllers/receivables_controller.rb
class ReceivablesController < ApplicationController
  before_action :set_receivable, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /receivables
  # GET /receivables.json
  def index
    @receivables = Receivable.all.where(secure: true, user_id: current_user.id)
  end

  # GET /receivables/1
  # GET /receivables/1.json
  def show
  end

  # GET /receivables/new
  def new
    @receivable = current_user.receivables.build
  end

  # GET /receivables/1/edit
  def edit
  end

  # POST /receivables
  # POST /receivables.json
  def create
    @receivable = current_user.receivables.new(receivable_params)
    @receivable[:secure] = true
    received_amount = Company.where(id: @receivable[:company_id]).select(:received_amount)
    comp_received_amount = received_amount[0].received_amount + @receivable[:receiveable_amount]

    bill_received_amount = Billentry.where(id: @receivable[:bill_no]).select(:received_amount)
    addbill_received_amount = (bill_received_amount[0].received_amount.present? ? bill_received_amount[0].received_amount : 0) + (@receivable[:receiveable_amount].present? ? @receivable[:receiveable_amount] : 0)
    respond_to do |format|
      if @receivable.save
        Company.where(id: @receivable[:company_id]).update(received_amount: comp_received_amount)
        Billentry.where(id: @receivable[:bill_no]).update(received_amount: addbill_received_amount)
        format.html { redirect_to @receivable, notice: 'Receivable was successfully created.' }
        format.json { render :show, status: :created, location: @receivable }
      else
        format.html { render :new }
        format.json { render json: @receivable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /receivables/1
  # PATCH/PUT /receivables/1.json
  def update
    comp_received_amount = Company.where(id: @receivable[:company_id]).select(:received_amount)
    m_cra_w_rra = (comp_received_amount[0].received_amount.present? ? comp_received_amount[0].received_amount : 0 ) - (@receivable[:receiveable_amount].present? ? @receivable[:receiveable_amount] : 0)
    updated_comp_ra = m_cra_w_rra + receivable_params[:receiveable_amount].to_d

    bill_received_amount = Billentry.where(id: @receivable[:bill_no]).select(:received_amount)
    m_bra_w_rra = (bill_received_amount[0].received_amount.present? ? bill_received_amount[0].received_amount : 0) - (@receivable[:receiveable_amount].present? ? @receivable[:receiveable_amount] : 0)
    update_bill_ra = m_bra_w_rra + receivable_params[:receiveable_amount].to_d
    respond_to do |format|
      if @receivable.update(receivable_params)
        Company.where(id: @receivable[:company_id]).update(received_amount: updated_comp_ra)
        Billentry.where(id: @receivable[:bill_no]).update(received_amount: update_bill_ra)
        format.html { redirect_to @receivable, notice: 'Receivable was successfully updated.' }
        format.json { render :show, status: :ok, location: @receivable }
      else
        format.html { render :edit }
        format.json { render json: @receivable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /receivables/1
  # DELETE /receivables/1.json
  def destroy
    @receivable.update(secure: true)
    respond_to do |format|
      format.html { redirect_to receivables_url, notice: 'Receivable was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_receivable
      @receivable = Receivable.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def receivable_params
      params.require(:receivable).permit(:company_id, :receiveable_amount, :check_date, :transaction_date, :remarks, :bill_no)
    end
end

app/helpers/receivables_helper.rb
module ReceivablesHelper
end

app/views/receivables/_form.html.erb
<%= form_for(receivable) do |f| %>
  <% if receivable.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(receivable.errors.count, "error") %> prohibited this receivable from being saved:</h2>

      <ul>
      <% receivable.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="form-group">
  <div class="row">
    <div class="col-md-3">
      <div class="field">
        <%= f.label :company_id %>
        <%= f.collection_select :company_id, Company.all.where(secure:true, user_id: current_user.id), :id, :company_name, { include_blank: 'Choose Company Name' } ,class: "form-control", placeholder: "Company Select", required: :true %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="field">
        <%= f.label :bill_no %>
        <%= f.collection_select :bill_no, Billentry.all.where(secure:true, user_id: current_user.id), :id, :id, { include_blank: 'Choose Bill No' } ,class: "form-control", required: :true %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="field">
        <%= f.label :receiveable_amount %>
        <%= f.text_field :receiveable_amount, class: "form-control", placeholder: "Received Amount", required: :true %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="field">
        <%= f.label :check_date %>
        <%= f.date_field :check_date, class: "form-control" %>
      </div>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-3">
      <div class="field">
        <%= f.label :transaction_date %>
        <%= f.date_field :transaction_date, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="field">
        <%= f.label :remarks %>
        <%= f.text_area :remarks, class: "form-control", placeholder: "Check No or Other Details" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4 col-md-offset-4 centered m-t-m text-center">
      <div class="actions">
        <%= f.submit class: "btn-success form-control" %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/receivables/edit.html.erb
<div class="main-header non-printable">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <%= link_to image_tag('logo.png', alt: 'Water HY-Drant Project'), root_path %>
        <p id="notice">
          <%= notice %>
        </p>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-8">
        <h1>Edit Receiveable Record</h1>
      </div>
      <div class="col-md-4 m-t-l text-center">
        <%= link_to '<< Back', receivables_path, class: "btn-info form-control pull-right", style: "width:100px;" %>
      </div>
    </div>
    <hr>
    <%= render 'form', receivable: @receivable %>
  </div>
</div>

app/views/receivables/index.html.erb
<div class="main-header non-printable">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <%= link_to image_tag('logo.png', alt: 'Water HY-Drant Project'), root_path %>
        <p id="notice">
          <%= notice %>
        </p>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-4">
        <h1>Receivables</h1>
      </div>
      <div class="col-md-4">

      </div>
      <div class="col-md-4 m-t-m text-center">
        <%= link_to '+ New Receiveable Entry', new_receivable_path, class: "btn-success form-control pull-right", style: "width:200px;" %>
      </div>
    </div>

    <table id="receivables" class="display">
      <thead>
      <tr>
        <th>Company</th>
        <th>Bill No</th>
        <th>Receiveable amount</th>
        <th>Check date</th>
        <th>Transaction date</th>
        <th>Remarks</th>
      </tr>
      </thead>

      <tbody>
      <% @receivables.each do |receivable| %>
          <tr>
            <td><%= link_to Company.where(id: receivable.company_id).pluck(:company_name).join(" "), receivable %></td>
            <td><%= link_to receivable.bill_no, receivable %></td>
            <td><%= link_to receivable.receiveable_amount, receivable %></td>
            <td><%= link_to receivable.check_date.present? ? receivable.check_date : '', receivable %></td>
            <td><%= link_to receivable.transaction_date.present? ? receivable.transaction_date : '', receivable %></td>
            <td><%= link_to receivable.remarks.present? ? receivable.remarks : '', receivable %></td>
          </tr>
      <% end %>
      </tbody>
    </table>

    <br>
  </div>
</div>

app/views/receivables/new.html.erb
<div class="main-header non-printable">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <%= link_to image_tag('logo.png', alt: 'Water HY-Drant Project'), root_path %>
        <p id="notice">
          <%= notice %>
        </p>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-4">
        <h1>New Receivable Entry</h1>
      </div>
      <div class="col-md-4 col-md-offset-4 centered m-t-l text-center">
        <%= link_to '<< Back', receivables_path, class: "btn-info form-control pull-right", style: "width:100px;" %>
      </div>
    </div>
    <hr>
    <%= render 'form', receivable: @receivable %>
  </div>
</div>

app/views/receivables/show.html.erb
<div class="main-header non-printable">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <%= link_to image_tag('logo.png', alt: 'Water HY-Drant Project'), root_path %>
        <p id="notice">
          <%= notice %>
        </p>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-8">
        <h1>Review Receivable Record</h1>
      </div>
      <div class="col-md-4 m-t-l text-center">
        <%= link_to '<< Back', receivables_path, class: "btn-info form-control pull-right", style: "width:100px;" %>
      </div>
    </div>
    <hr>
    <div class="row form-group">
      <div class="col-md-3">
        <h3>Company</h3>
        <input type="text" value="<%= Company.where(id: @receivable.company_id).pluck(:company_name).join(" ") %>" class="form-control" disabled>
      </div>
      <div class="col-md-3">
        <h3>Bill No</h3>
        <input type="text" value="<%= @receivable.bill_no %>" class="form-control" disabled>
      </div>
      <div class="col-md-3">
        <h3>Receivable Amount</h3>
        <input type="text" value="<%= @receivable.receiveable_amount %>" class="form-control" disabled>
      </div>
      <div class="col-md-3">
        <h3>Check Date</h3>
        <input type="text" value="<%= @receivable.check_date %>" class="form-control" disabled>
      </div>
    </div>
    <div class="row form-group">
      <div class="col-md-3">
        <h3>Transaction Date</h3>
        <input type="text" value="<%= @receivable.transaction_date %>" class="form-control" disabled>
      </div>
      <div class="col-md-4">
        <h3>Remarks</h3>
        <textarea cols="45" rows="3" class="form-control" disabled><%= @receivable.remarks %></textarea>
      </div>
    </div>
    <div class="row">
      <div class="col-md-2">
        &nbsp;
      </div>
      <div class="col-md-4 m-t-m text-center">
        <div class="actions">
          <%= link_to 'Edit', edit_receivable_path(@receivable), class: "btn-success form-control" %>
        </div>
      </div>
      <div class="col-md-4 m-t-m text-center">
        <div class="action">
          <%= link_to 'Destroy', params[:id], method: :delete, data: { confirm: 'Are you sure?' }, class: "btn-danger form-control" %>
        </div>
      </div>
      <div class="col-md-2">
        &nbsp;
      </div>
    </div>
    <br>
  </div>
</div>