config/routes.rb
Rails.application.routes.draw do
  resources :receivables
  resources :billentries do
    collection do
      get 'company_data'
    end
  end
  resources :companies, only: [:show, :index, :create, :new]
  resources :trucks
  # get 'reports', to: 'reports#index'
  get 'bill_reports', to: 'reports#bill_report'
  get 'report_print', to: 'reports#report_print'

  resources :reports, only: [:index]
  # do
    # collection do
    #   get 'report_data'
    # end
  # end

  root to: 'welcome#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/billentry.rb
class Billentry < ApplicationRecord
  belongs_to :user
end

app/controllers/billentries_controller.rb
class BillentriesController < ApplicationController
  before_action :set_billentry, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /billentries
  # GET /billentries.json
  def index
    @billentries = Billentry.all.where(secure: true, user_id: current_user.id)
  end

  # GET /billentries/1
  # GET /billentries/1.json
  def show
  end

  # GET /billentries/new
  def new
    @billentry = current_user.billentries.build
  end

  # GET /billentries/1/edit
  def edit
  end

  # POST /billentries
  # POST /billentries.json
  def create
    @billentry = current_user.billentries.build(billentry_params)
    @billentry[:secure] = true
    bill_amount = Company.where(id: @billentry[:company_id]).select(:total_bill_amount)
    comp_bill_amount = bill_amount[0].total_bill_amount + @billentry[:total_amount]

    respond_to do |format|
      if @billentry.save
        Company.where(id: @billentry[:company_id]).update(total_bill_amount: comp_bill_amount)
        format.html { redirect_to @billentry, notice: 'Billentry was successfully created.' }
        format.json { render :show, status: :created, location: @billentry }
      else
        format.html { render :new }
        format.json { render json: @billentry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /billentries/1
  # PATCH/PUT /billentries/1.json
  def update
    company_total_amount = Company.where(id: @billentry[:company_id]).select(:total_bill_amount)
    m_cta_w_bta = (company_total_amount[0].total_bill_amount.present? ? company_total_amount[0].total_bill_amount : 0) - (@billentry[:total_amount].present? ? @billentry[:total_amount] : 0)
    updated_comp_bta = m_cta_w_bta + billentry_params[:total_amount].to_d
    respond_to do |format|
      if @billentry.update(billentry_params)
        Company.where(id: @billentry[:company_id]).update(total_bill_amount: updated_comp_bta)
        format.html { redirect_to @billentry, notice: 'Billentry was successfully updated.' }
        format.json { render :show, status: :ok, location: @billentry }
      else
        format.html { render :edit }
        format.json { render json: @billentry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /billentries/1
  # DELETE /billentries/1.json
  def destroy
    @billentry.update(secure: false)
    respond_to do |format|
      format.html { redirect_to billentries_url, notice: 'Billentry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def company_data
    company_id = params[:data_id] || []
    data = Company.where(secure: true, user_id: current_user.id ,id: company_id)
    if request.xhr?
      render :json => {
          :company_data => data
      }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_billentry
      @billentry = Billentry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def billentry_params
      params.require(:billentry).permit(:truck_no, :address, :time_arrive, :time_departure, :current_date, :supply_rate, :company_id, :capacity, :previous_balance, :total_amount, :received_amount)
    end
end

app/helpers/billentries_helper.rb
module BillentriesHelper
end

app/views/billentries/_form.html.erb
<%= form_for(billentry, remote: true) do |f| %>
  <% if billentry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(billentry.errors.count, "error") %> prohibited this billentry from being saved:</h2>

      <ul>
      <% billentry.errors.full_messages.each do |message| %>params[:id]
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group">
  <div class="row">
    <div class="col-md-2">
      <div class="field">
        <%= f.label :truck_no %>
        <%= f.collection_select :truck_no, Truck.all.where(secure:true, user_id: current_user.id), :id, :truck_no, { include_blank: 'Choice Truck' }, { class: "form-control", required: :true }  %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="field">
        <%= f.label :company_name %>
        <% if billentry.persisted? %>
          <%= f.collection_select :company_id, Company.all.where(secure:true, user_id: current_user.id), :id, :company_name, { include_blank: 'Choice Company Name' },class: "form-control", disabled: true %>
        <% else %>
          <%= f.collection_select :company_id, Company.all.where(secure:true, user_id: current_user.id), :id, :company_name, { include_blank: 'Choice Company Name' },class: "form-control", required: :true %>
        <% end %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="field">
        <%= f.label :address %>
        <%= f.text_area :address,class: "form-control", placeholder: 'Address Populate When You Select Company',readonly: true%>
      </div>
    </div>
    <div class="col-md-2">
      <div class="field">
        <%= f.label :time_arrive %>
        <%= f.collection_select :time_arrive, Daytime.all, :day_start, :day_start, {include_blank: 'Arrive Time'}, { class: "form-control", required: :true }  %>
      </div>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-3">
      <div class="field">
        <%= f.label :time_departure %>
        <%= f.collection_select :time_departure, Daytime.all, :day_start, :day_start, {include_blank: 'Choice Day Start Time'}, { class: "form-control", required: :true }  %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="field">
        <%= f.label :current_date %>
        <%= f.date_field :current_date, class: "form-control", required: :true %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="field">
        <%= f.label :supply_rate %>
        <%= f.text_field :supply_rate, class: "form-control", placeholder: 'Supply Rate',required: :true %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="field">
        <%= f.label :capacity %>
        <%= f.text_field :capacity, class: "form-control capa", placeholder: 'Capacity In LTR' ,required: :true %>
      </div>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-3">
      <div class="field">
        <%= f.label :previous_balance %>
        <%= f.text_field :previous_balance, class: "form-control",placeholder: 'Select Company For Previous' ,readonly: true%>
      </div>
    </div>
    <div class="col-md-3">
      <div class="field">
        <%= f.label :total_amount %>
        <%= f.text_field :total_amount, class: "form-control", placeholder: 'Current Bill Total Amount' ,required: :true %>
      </div>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-4 col-md-offset-4 centered m-t-m text-center">
      <div class="actions">
        <%= f.submit class: "btn-success form-control" %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/billentries/edit.html.erb
<div class="row">
  <div class="col-md-4">
    <h1>Edit Bill Entry Record</h1>
  </div>
  <div class="col-md-4">

  </div>
  <div class="col-md-4 col-md-offset-4 centered m-t-l text-center">
    <%= link_to '<< Back', billentries_path, class: "btn-info form-control pull-right", style: "width:100px;" %>
  </div>
</div>
<hr>
<%= render 'form', billentry: @billentry %>

app/views/billentries/index.html.erb
<div class="main-header non-printable">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <%= link_to image_tag('logo.png', alt: 'Water HY-Drant Project'), root_path %>
        <p id="notice">
          <%= notice %>
        </p>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-4">
        <h1>Billentries</h1>
      </div>
      <div class="col-md-4">

      </div>
      <div class="col-md-4 m-t-m text-center">
        <%= link_to '+ New Billentry', new_billentry_path, class: "btn-success form-control pull-right", style: "width:200px;" %>
      </div>
    </div>
    <hr>
    <table class="display" id="billentries">
      <thead>
      <tr>
        <th>Bill No</th>
        <th>Company name</th>
        <th>Time arrive</th>
        <th>Time departure</th>
        <th>Current date</th>
        <th>Supply rate</th>
        <th>Capacity</th>
        <th>Previous Balance</th>
        <th>Total amount</th>
        <th>Received Amount</th>
        <th>Net Balance</th>
      </tr>
      </thead>

      <tbody>
      <% @billentries.each do |billentry| %>
          <tr>
            <td><%=link_to billentry.id, billentry %></td>
            <td><%=link_to Company.where(id: billentry.company_id).pluck(:company_name).flatten.join(' '), billentry %></td>
            <td><%=link_to billentry.time_arrive, billentry %></td>
            <td><%=link_to billentry.time_departure, billentry %></td>
            <td><%=link_to billentry.current_date, billentry %></td>
            <td><%=link_to number_to_currency(billentry.supply_rate, precision: 2, unit: ''), billentry %></td>
            <td><%=link_to number_to_currency(billentry.capacity, precision: 2, unit: 'LTR '), billentry %></td>
            <td><%=link_to number_to_currency(billentry.previous_balance, precision: 2, unit: 'PKR '), billentry %></td>
            <td><%=link_to number_to_currency(billentry.total_amount.present? ? billentry.total_amount : 0, precision: 2, unit: 'PKR '), billentry %></td>
            <td><%=link_to number_to_currency(billentry.received_amount.present? ? billentry.received_amount : 0 , precision: 2, unit: 'PKR '), billentry %></td>
            <td><%=link_to number_to_currency((billentry.total_amount.present? ? billentry.total_amount : 0) - (billentry.received_amount.present? ? billentry.received_amount : 0), precision: 2, unit: 'PKR '), billentry %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
    <br>


  </div>
</div>

app/views/billentries/new.html.erb
<div class="main-header non-printable">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <%= link_to image_tag('logo.png', alt: 'Water HY-Drant Project'), root_path %>
        <p id="notice">
          <%= notice %>
        </p>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-4">
        <h1>New Billentry Entry</h1>
      </div>
      <div class="col-md-4 col-md-offset-4 centered m-t-l text-center">
        <%= link_to '<< Back', billentries_path, class: "btn-info form-control pull-right", style: "width:100px;" %>
      </div>
    </div>
    <hr>

    <%= render 'form', billentry: @billentry %>
  </div>
</div>

app/views/billentries/show.html.erb
<div class="main-header non-printable">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <%= link_to image_tag('logo.png', alt: 'Water HY-Drant Project'), root_path %>
        <p id="notice">
          <%= notice %>
        </p>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-8">
        <h1>Review Bill Entries</h1>
      </div>
      <div class="col-md-4 m-t-l text-center">
        <%= link_to '<< Back', billentries_path, class: "btn-info form-control pull-right", style: "width:100px;" %>
      </div>
    </div>
    <div class="row form-group">
      <div class="col-md-3">
        <h3>Truck No</h3>
        <input type="text" value="<%= Truck.where(id: @billentry.truck_no).pluck(:truck_no).flatten.join(' ') %>" class="form-control" disabled>
      </div>
      <div class="col-md-3">
        <h3>Company Name</h3>
        <input type="text" value="<%= Company.where(id: @billentry.company_id).pluck(:company_name).flatten.join(' ') %>" class="form-control" disabled>
      </div>
      <div class="col-md-3">
        <h3>Address</h3>
        <textarea class="form-control" disabled><%= @billentry.address %></textarea>
      </div>
      <div class="col-md-3">
        <h3>Time Arrive</h3>
        <input type="text" value="<%= @billentry.time_arrive %>" class="form-control" disabled>
      </div>
    </div>
    <div class="row form-group">
      <div class="col-md-3">
        <h3>Time Departure</h3>
        <input type="text" value="<%= @billentry.time_departure %>" class="form-control" disabled>
      </div>
      <div class="col-md-3">
        <h3>Current Date</h3>
        <input type="text" value="<%= @billentry.current_date %>" class="form-control" disabled>
      </div>
      <div class="col-md-3">
        <h3>Supply Rate</h3>
        <input type="text" value="<%= number_to_currency(@billentry.supply_rate, precision: 2, unit:'') %>" class="form-control" disabled>
      </div>
      <div class="col-md-3">
        <h3>Capacity</h3>
        <input type="text" value="<%= number_to_currency(@billentry.capacity, precision: 2, unit:'LTR ') %>" class="form-control" disabled>
      </div>
    </div>
    <div class="row form-group">
      <div class="col-md-3">
        <h3>Previous Amount</h3>
        <input type="text" value="<%= number_to_currency(@billentry.previous_balance, precision: 2, unit: 'PKR ') %>" class="form-control" disabled>
      </div>
      <div class="col-md-3">
        <h3>Total Amount</h3>
        <input type="text" value="<%= number_to_currency(@billentry.total_amount, precision: 2, unit: 'PKR ') %>" class="form-control" disabled>
      </div>
    </div>
    <div class="row">
      <div class="col-md-2">
        &nbsp;
      </div>
      <div class="col-md-4 m-t-m text-center">
        <div class="actions">
          <%= link_to 'Edit', edit_billentry_path(@billentry), class: "btn-success form-control" %>
        </div>
      </div>
      <div class="col-md-4 m-t-m text-center">
        <div class="action">
          <%= link_to 'Destroy', params[:id], method: :delete, data: { confirm: 'Are you sure?' }, class: "btn-danger form-control" %>
        </div>
      </div>
      <div class="col-md-2">
        &nbsp;
      </div>
    </div>
    <br>
  </div>
</div>